import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import getCommerce from "../utils/commerce";

export default function Home(props) {
  const { products } = props;

  return (
    <div className={styles.container}>
      <Head>
        <title>Coolshop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {products.map((product) => (
          <div key={product.id}>
            <Image
              src={product.media.source}
              alt={product.name}
              width={200}
              height={200}
            ></Image>
            <p>{product.name}</p>
            <p>{product.price.formatted_with_symbol}</p>
          </div>
        ))}
      </main>
      <footer className={styles.footer}>footer</footer>
    </div>
  );
}

export async function getStaticProps() {
  const commerce = getCommerce();

  const { data: products } = await commerce.products.list();

  return {
    props: {
      products,
    },
  };
}
